FROM rust:1.77-slim-buster

RUN apt-get update && apt-get install -y python3 lua5.3 && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/executor
COPY executor_script.sh .
RUN chmod +x executor_script.sh

CMD ["./executor_script.sh"]
